login/urls.py
from django.conf.urls import url

from . import views
app_name='login'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^validate/$', views.validate, name='validate'),
    url(r'^success/$', views.success, name='success')
]

redSocial/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^register/', include('register.urls')),
    url(r'^login/', include('login.urls')),
    url(r'^upload/', include('upload.urls')),
    url(r'^admin/', admin.site.urls),
]

register/urls.py
from django.conf.urls import url

from . import views
app_name='register'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(r'^success/$', views.success, name='success'),
]

upload/urls.py
from django.conf.urls import url

from . import views
app_name='upload'
urlpatterns = [
    url(r'^$', views.upload_file, name='uploadFile'),
    
]

login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

register/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

upload/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Document(models.Model):
    filename = models.CharField(max_length=100)
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')

upload/forms.py
from django import forms

class UploadForm(forms.Form):
    filename = forms.CharField(max_length=100)
    docfile = forms.FileField(
        label = 'Selecciona un archivo'
    )

login/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse

def index(request):
    context = {}               
    if request.user.is_authenticated:
        return render(request, 'login/success.html', context)
    else:
        return render(request, 'login/index.html', context)
def validate(request):
    username = request.POST['userName']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return render(request, 'login/success.html', None)
    else:
        return render(request, 'login/index.html', {errorMessage : "User or password incorrect"})
    
def success(request):
    return HttpResponse("You have log in succesfully.")


# Create your views here.

register/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import login

from django.http import HttpResponse

def index(request):
    context = {}
    return render(request,'register/index.html',context)
def create(request):
    user = User.objects.create_user(username=request.POST['userName'], email=request.POST['email'], password=request.POST['password'], first_name=request.POST['firstName'], last_name=request.POST['lastName'])
    if user is not None:
        login(request, user)
        return render(request, 'register/success.html', None)
    else:
        return render(request, 'register/fail.html', None)
    
def success(request):
    return HttpResponse("You have register succesfully.")
# Create your views here.

upload/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import UploadForm
from .models import Document

# Create your views here.

def upload_file(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if(form.is_valid()):
            newdoc = Document(filename = request.POST['filename'], docfile = request.FILES['docfile'])
            newdoc.save(form)
            return redirect("upload:uploadFile")
    else:
        form = UploadForm()
    return render(request, 'upload/upload.html', {'form':form})
            
                                

login/templates/login/index.html
<html>
  <head>
    <tittle>Register page </tittle>
    <meta charset="utf-8"/>
  </head>
  <body>
    <p style='color:red'>{{errorMessage}}</p>
    <h1>Register</h1>
    <p>Llene los campos para registrar nuevo usuario</p>
    <br/>
    <form action="{% url 'login:validate' %}" method="post">
      {% csrf_token %}
      <label>user</label> : <input type="text" name="userName" id="userName" />
      <label>password</label> : <input type="password" name="password" id="password"/>
      <input type="submit" value="log in"/>
    </form>    
  </body>
</html>

login/templates/login/success.html
<html>
  <head>
    <title>User {{request.user.username}}</title>
    <meta charset="utf-8"/>
  </head>
  <body>
    <p> the user {{request.user.username}} has been log in succesfully</p>
  </body>

register/templates/register/index.html
<html>
  <head>
    <title>Register page </title>
    <meta charset="utf-8"/>
  </head>
  <body>
    <h1>Register</h1>
    <p>Llene los campos para registrar nuevo usuario</p>
    <br/>
    <form action="{% url 'register:create' %}" method="post">
      {% csrf_token %}
      <label>First Name</label> : <input type="text" name="firstName" id="firstName"/>
      <br/>
      <label>Last Name</label> : <input type="text" name="lastName" id="lastName"/>
      <br/>
      <label>email</label> : <input type="text" name="email" id="email"/>
      <br/>
      <label>user</label> : <input type="text" name="userName" id="userName"/>
      <br/>
      <label>password</label> : <input type="password" name="password" id="password"/>
      <br/>
      <br/>
      <input type="submit" value="create"/>
    </form>    
  </body>
</html>

register/templates/register/success.html
<html>
  <head>
    <title>Register succesfull </title>
    <meta charset="utf-8"/>
  </head>
  <body>
    <p>{{request.user.first_name }} {{request.user.last_name }} has created the user {{request.user.username}}
  </body>
</html>

upload/templates/upload/fail.html
<html>
  <head>
    <tittle>Error page </tittle>
    <meta charset="utf-8"/>
  </head>
  <body>
    <p style='color:red'>{{errorMessage}}</p>
 </body>
</html>

upload/templates/upload/success.html
<html>
  <head>
    <title>The File Upload Was Successfull</title>
    <meta charset="utf-8"/>
  </head>
  <body>
    <p>{{request.user.first_name }} {{request.user.last_name }} has upload the file 
  </body>
</html>

upload/templates/upload/upload.html
<!DOCTYPE>
<html>
  <head>
    <title>Upload File</title>
  </head>
  <body>
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Submit"/>
  </body>
</html>